query Repos($value: String!, $after: String = null  ) {
  search(query: $value, type: REPOSITORY, first: 10, after: $after) {
    edges {
      node {
        ... on Repository {
          id
          name
          createdAt
          description
          owner {
            login
            avatarUrl
          }
        }
      }
    }
    pageInfo {
      endCursor
      hasNextPage
    }
  }
}

